In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('C:\\Users\\Raushan Kumar\\Downloads\\Code\\LS_2.0.csv')

In [3]:
df.describe()

WINNER          AGE  GENERAL\nVOTES  POSTAL\nVOTES  TOTAL\nVOTES  \
count  2263.000000  2018.000000    2.263000e+03    2263.000000  2.263000e+03   
mean      0.238179    52.273538    2.615991e+05     990.710561  2.625898e+05   
std       0.426064    11.869373    2.549906e+05    1602.839174  2.559822e+05   
min       0.000000    25.000000    1.339000e+03       0.000000  1.342000e+03   
25%       0.000000    43.250000    2.103450e+04      57.000000  2.116250e+04   
50%       0.000000    52.000000    1.539340e+05     316.000000  1.544890e+05   
75%       0.000000    61.000000    4.858040e+05    1385.000000  4.872315e+05   
max       1.000000    86.000000    1.066824e+06   19367.000000  1.068569e+06   

       OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
count                            2263.000000   
mean                               15.811412   
std                                14.962861   
min                                 0.097941   
25%                                 1.296518   
50%                                10.510553   
75%                                29.468185   
max                                51.951012   

       OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
count                                2263.000000    2.263000e+03  
mean                                   23.190525    1.658016e+06  
std                                    21.564758    3.145187e+05  
min                                     1.000039    5.518900e+04  
25%                                     1.899502    1.530014e+06  
50%                                    16.221721    1.679030e+06  
75%                                    42.590233    1.816857e+06  
max                                    74.411856    3.150313e+06

In [7]:
df.dtypes

STATE                                         object
CONSTITUENCY                                  object
NAME                                          object
WINNER                                         int64
PARTY                                         object
SYMBOL                                        object
GENDER                                        object
CRIMINAL\nCASES                               object
AGE                                          float64
CATEGORY                                      object
EDUCATION                                     object
ASSETS                                        object
LIABILITIES                                   object
GENERAL\nVOTES                                 int64
POSTAL\nVOTES                                  int64
TOTAL\nVOTES                                   int64
OVER TOTAL ELECTORS \nIN CONSTITUENCY        float64
OVER TOTAL VOTES POLLED \nIN CONSTITUENCY    float64
TOTAL ELECTORS                                

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2263 entries, 0 to 2262
Data columns (total 19 columns):
 #   Column                                    Non-Null Count  Dtype  
---  ------                                    --------------  -----  
 0   STATE                                     2263 non-null   object 
 1   CONSTITUENCY                              2263 non-null   object 
 2   NAME                                      2263 non-null   object 
 3   WINNER                                    2263 non-null   int64  
 4   PARTY                                     2263 non-null   object 
 5   SYMBOL                                    2018 non-null   object 
 6   GENDER                                    2018 non-null   object 
 7   CRIMINAL
CASES                            2018 non-null   object 
 8   AGE                                       2018 non-null   float64
 9   CATEGORY                                  2018 non-null   object 
 10  EDUCATION                           

In [10]:
df.head()

STATE CONSTITUENCY                   NAME  WINNER PARTY SYMBOL  \
0      Telangana     ADILABAD         SOYAM BAPU RAO       1   BJP  Lotus   
1      Telangana     ADILABAD           Godam Nagesh       0   TRS    Car   
2      Telangana     ADILABAD          RATHOD RAMESH       0   INC   Hand   
3      Telangana     ADILABAD                   NOTA       0  NOTA    NaN   
4  Uttar Pradesh         AGRA  Satyapal Singh Baghel       1   BJP  Lotus   

  GENDER CRIMINAL\nCASES   AGE CATEGORY      EDUCATION  \
0   MALE              52  52.0       ST      12th Pass   
1   MALE               0  54.0       ST  Post Graduate   
2   MALE               3  52.0       ST      12th Pass   
3    NaN             NaN   NaN      NaN            NaN   
4   MALE               5  58.0       SC      Doctorate   

                        ASSETS                  LIABILITIES  GENERAL\nVOTES  \
0    Rs 30,99,414\n ~ 30 Lacs+      Rs 2,31,450\n ~ 2 Lacs+          376892   
1  Rs 1,84,77,888\n ~ 1 Crore+      Rs 8,47,000\n ~ 8 Lacs+          318665   
2  Rs 3,64,91,000\n ~ 3 Crore+  Rs 1,53,00,000\n ~ 1 Crore+          314057   
3                          NaN                          NaN           13030   
4  Rs 7,42,74,036\n ~ 7 Crore+    Rs 86,06,522\n ~ 86 Lacs+          644459   

   POSTAL\nVOTES  TOTAL\nVOTES  OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
0            482        377374                              25.330684   
1            149        318814                              21.399929   
2            181        314238                              21.092771   
3              6         13036                               0.875023   
4           2416        646875                              33.383823   

   OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
0                                  35.468248         1489790  
1                                  29.964370         1489790  
2                                  29.534285         1489790  
3                                   1.225214         1489790  
4                                  56.464615         1937690

In [17]:
df[df['OVER TOTAL ELECTORS \nIN CONSTITUENCY'].isin(['OVER TOTAL VOTES POLLED \nIN CONSTITUENCY'])]

Empty DataFrame
Columns: [STATE, CONSTITUENCY, NAME, WINNER, PARTY, SYMBOL, GENDER, CRIMINAL
CASES, AGE, CATEGORY, EDUCATION, ASSETS, LIABILITIES, GENERAL
VOTES, POSTAL
VOTES, TOTAL
VOTES, OVER TOTAL ELECTORS 
IN CONSTITUENCY, OVER TOTAL VOTES POLLED 
IN CONSTITUENCY, TOTAL ELECTORS]
Index: []

In [29]:
df.at[0,'POSTAL\nVOTES'] #get index number value from column

482.0

In [31]:
df.iat[0, 1] ##get index number value from column location

'ADILABAD'

In [33]:
df.dropna(how='any') #To drop any rows that have missing data.
#df.fillna(value=5)
#pd.isna(df1)

STATE     CONSTITUENCY                   NAME  WINNER PARTY  \
0         Telangana         ADILABAD         SOYAM BAPU RAO     1.0   BJP   
1         Telangana         ADILABAD           Godam Nagesh     0.0   TRS   
2         Telangana         ADILABAD          RATHOD RAMESH     0.0   INC   
4     Uttar Pradesh             AGRA  Satyapal Singh Baghel     1.0   BJP   
5     Uttar Pradesh             AGRA       Manoj Kumar Soni     0.0   BSP   
...             ...              ...                    ...     ...   ...   
2258    Maharashtra  YAVATMAL-WASHIM     Anil Jayram Rathod     0.0   IND   
2259      Telangana        ZAHIRABAD              B.B.PATIL     1.0   TRS   
2260      Telangana        ZAHIRABAD        MADAN MOHAN RAO     0.0   INC   
2261      Telangana        ZAHIRABAD     BANALA LAXMA REDDY     0.0   BJP   
A                 0                0                      0     0.0     0   

        SYMBOL GENDER CRIMINAL\nCASES   AGE CATEGORY      EDUCATION  \
0        Lotus   MALE              52  52.0       ST      12th Pass   
1          Car   MALE               0  54.0       ST  Post Graduate   
2         Hand   MALE               3  52.0       ST      12th Pass   
4        Lotus   MALE               5  58.0       SC      Doctorate   
5     Elephant   MALE               0  47.0       SC  Post Graduate   
...        ...    ...             ...   ...      ...            ...   
2258      SHIP   MALE               0  43.0  GENERAL  Post Graduate   
2259       Car   MALE              18  63.0  GENERAL       Graduate   
2260      Hand   MALE               0  49.0  GENERAL  Post Graduate   
2261     Lotus   MALE               3  47.0  GENERAL      12th Pass   
A            0      0               0   0.0        0              0   

                                ASSETS                  LIABILITIES  \
0            Rs 30,99,414\n ~ 30 Lacs+      Rs 2,31,450\n ~ 2 Lacs+   
1          Rs 1,84,77,888\n ~ 1 Crore+      Rs 8,47,000\n ~ 8 Lacs+   
2          Rs 3,64,91,000\n ~ 3 Crore+  Rs 1,53,00,000\n ~ 1 Crore+   
4          Rs 7,42,74,036\n ~ 7 Crore+    Rs 86,06,522\n ~ 86 Lacs+   
5        Rs 13,37,84,385\n ~ 13 Crore+  Rs 2,22,51,891\n ~ 2 Crore+   
...                                ...                          ...   
2258         Rs 48,90,000\n ~ 48 Lacs+    Rs 10,20,000\n ~ 10 Lacs+   
2259  Rs 1,28,78,51,556\n ~ 128 Crore+  Rs 1,15,35,000\n ~ 1 Crore+   
2260     Rs 90,36,63,001\n ~ 90 Crore+                     Rs 0\n ~   
2261       Rs 5,85,77,327\n ~ 5 Crore+    Rs 52,50,000\n ~ 52 Lacs+   
A                                    0                            0   

      GENERAL\nVOTES  POSTAL\nVOTES  TOTAL\nVOTES  \
0           376892.0          482.0      377374.0   
1           318665.0          149.0      318814.0   
2           314057.0          181.0      314238.0   
4           644459.0         2416.0      646875.0   
5           434199.0         1130.0      435329.0   
...              ...            ...           ...   
2258         14661.0           25.0       14686.0   
2259        434066.0          178.0      434244.0   
2260        427900.0          115.0      428015.0   
2261        138731.0          216.0      138947.0   
A                0.0            0.0           0.0   

      OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
0                                 25.330684   
1                                 21.399929   
2                                 21.092771   
4                                 33.383823   
5                                 22.466390   
...                                     ...   
2258                               0.766419   
2259                              28.975369   
2260                              28.559732   
2261                               9.271379   
A                                  0.000000   

      OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
0                                     35.468248       1489790.0  
1                                     29.964370  

In [34]:
df['PARTY'].shift(2)

0         NaN
1         NaN
2         BJP
3         TRS
4         INC
        ...  
2259    PHJSP
2260      IND
2261      TRS
2262      INC
A         BJP
Name: PARTY, Length: 2264, dtype: object

In [36]:
import numpy as np

In [38]:
np.random.randint(0, 7, size=(2,4))

array([[6, 3, 6, 2],
       [0, 2, 5, 3]])

In [46]:
df['STATE'].value_counts()

Uttar Pradesh                274
Bihar                        244
Tamil Nadu                   217
West Bengal                  193
Maharashtra                  192
Andhra Pradesh               121
Madhya Pradesh               103
Gujarat                       87
Rajasthan                     86
Odisha                        85
Telangana                     83
Karnataka                     77
Jharkhand                     73
Kerala                        63
Punjab                        62
Assam                         52
Chhattisgarh                  45
Haryana                       41
Jammu & Kashmir               29
NCT OF Delhi                  24
Uttarakhand                   16
Arunachal Pradesh             11
Tripura                       10
Himachal Pradesh              10
Manipur                       10
Goa                            8
Dadra & Nagar Haveli           7
Meghalaya                      7
Mizoram                        5
Andaman & Nicobar Islands      5
Puducherry

In [48]:
pd.concat([df,df], axis = 1)

STATE CONSTITUENCY                   NAME  WINNER PARTY SYMBOL  \
0         Telangana     ADILABAD         SOYAM BAPU RAO     1.0   BJP  Lotus   
1         Telangana     ADILABAD           Godam Nagesh     0.0   TRS    Car   
2         Telangana     ADILABAD          RATHOD RAMESH     0.0   INC   Hand   
3         Telangana     ADILABAD                   NOTA     0.0  NOTA    NaN   
4     Uttar Pradesh         AGRA  Satyapal Singh Baghel     1.0   BJP  Lotus   
...             ...          ...                    ...     ...   ...    ...   
2259      Telangana    ZAHIRABAD              B.B.PATIL     1.0   TRS    Car   
2260      Telangana    ZAHIRABAD        MADAN MOHAN RAO     0.0   INC   Hand   
2261      Telangana    ZAHIRABAD     BANALA LAXMA REDDY     0.0   BJP  Lotus   
2262      Telangana    ZAHIRABAD                   NOTA     0.0  NOTA    NaN   
A                 0            0                      0     0.0     0      0   

     GENDER CRIMINAL\nCASES   AGE CATEGORY  ... CATEGORY      EDUCATION  \
0      MALE              52  52.0       ST  ...       ST      12th Pass   
1      MALE               0  54.0       ST  ...       ST  Post Graduate   
2      MALE               3  52.0       ST  ...       ST      12th Pass   
3       NaN             NaN   NaN      NaN  ...      NaN            NaN   
4      MALE               5  58.0       SC  ...       SC      Doctorate   
...     ...             ...   ...      ...  ...      ...            ...   
2259   MALE              18  63.0  GENERAL  ...  GENERAL       Graduate   
2260   MALE               0  49.0  GENERAL  ...  GENERAL  Post Graduate   
2261   MALE               3  47.0  GENERAL  ...  GENERAL      12th Pass   
2262    NaN             NaN   NaN      NaN  ...      NaN            NaN   
A         0               0   0.0        0  ...        0              0   

                                ASSETS                  LIABILITIES  \
0            Rs 30,99,414\n ~ 30 Lacs+      Rs 2,31,450\n ~ 2 Lacs+   
1          Rs 1,84,77,888\n ~ 1 Crore+      Rs 8,47,000\n ~ 8 Lacs+   
2          Rs 3,64,91,000\n ~ 3 Crore+  Rs 1,53,00,000\n ~ 1 Crore+   
3                                  NaN                          NaN   
4          Rs 7,42,74,036\n ~ 7 Crore+    Rs 86,06,522\n ~ 86 Lacs+   
...                                ...                          ...   
2259  Rs 1,28,78,51,556\n ~ 128 Crore+  Rs 1,15,35,000\n ~ 1 Crore+   
2260     Rs 90,36,63,001\n ~ 90 Crore+                     Rs 0\n ~   
2261       Rs 5,85,77,327\n ~ 5 Crore+    Rs 52,50,000\n ~ 52 Lacs+   
2262                               NaN                          NaN   
A                                    0                            0   

      GENERAL\nVOTES  POSTAL\nVOTES  TOTAL\nVOTES  \
0           376892.0          482.0      377374.0   
1           318665.0          149.0      318814.0   
2           314057.0          181.0      314238.0   
3            13030.0            6.0       13036.0   
4           644459.0         2416.0      646875.0   
...              ...            ...           ...   
2259        434066.0          178.0      434244.0   
2260        427900.0          115.0      428015.0   
2261        138731.0          216.0      138947.0   
2262         11138.0            2.0       11140.0   
A                0.0            0.0           0.0   

      OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
0                                 25.330684   
1                                 21.399929   
2                                 21.092771   
3                                  0.875023   
4                                 33.383823   
...                                     ...   
2259                              28.975369   
2260                              28.559732   
2261                               9.271379   
2262                               0.743328   
A                                  0.000000   

      OVER TOTAL VOTES POLLED \nIN CONSTITUENCY TOTAL ELECTORS  
0                               

In [ ]:
pd.merge(left, right, on='key')

In [ ]:
pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])

In [55]:
df.to_numpy()

array([['Telangana', 'ADILABAD', 'SOYAM BAPU RAO', ..., 25.33068419,
        35.4682479, 1489790.0],
       ['Telangana', 'ADILABAD', 'Godam Nagesh', ..., 21.39992885,
        29.96436953, 1489790.0],
       ['Telangana', 'ADILABAD', 'RATHOD RAMESH', ..., 21.09277146,
        29.53428505, 1489790.0],
       ...,
       ['Telangana', 'ZAHIRABAD', 'BANALA LAXMA REDDY', ..., 9.271378679,
        13.30267763, 1498666.0],
       ['Telangana', 'ZAHIRABAD', 'NOTA', ..., 0.743327733,
        1.0665349290000001, 1498666.0],
       [0, 0, 0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [65]:
np.zeros((3,3)),np.ones((3,3))

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [71]:
df[2:5]

STATE CONSTITUENCY                   NAME  WINNER PARTY SYMBOL  \
2      Telangana     ADILABAD          RATHOD RAMESH     0.0   INC   Hand   
3      Telangana     ADILABAD                   NOTA     0.0  NOTA    NaN   
4  Uttar Pradesh         AGRA  Satyapal Singh Baghel     1.0   BJP  Lotus   

  GENDER CRIMINAL\nCASES   AGE CATEGORY  EDUCATION  \
2   MALE               3  52.0       ST  12th Pass   
3    NaN             NaN   NaN      NaN        NaN   
4   MALE               5  58.0       SC  Doctorate   

                        ASSETS                  LIABILITIES  GENERAL\nVOTES  \
2  Rs 3,64,91,000\n ~ 3 Crore+  Rs 1,53,00,000\n ~ 1 Crore+        314057.0   
3                          NaN                          NaN         13030.0   
4  Rs 7,42,74,036\n ~ 7 Crore+    Rs 86,06,522\n ~ 86 Lacs+        644459.0   

   POSTAL\nVOTES  TOTAL\nVOTES  OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
2          181.0      314238.0                              21.092771   
3            6.0       13036.0                               0.875023   
4         2416.0      646875.0                              33.383823   

   OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
2                                  29.534285       1489790.0  
3                                   1.225214       1489790.0  
4                                  56.464615       1937690.0

In [75]:
df['GENERAL\nVOTES'].cumsum()

0          376892.0
1          695557.0
2         1009614.0
3         1022644.0
4         1667103.0
           ...     
2259    591420956.0
2260    591848856.0
2261    591987587.0
2262    591998725.0
A       591998725.0
Name: GENERAL\nVOTES, Length: 2264, dtype: float64

In [76]:
df['GENERAL\nVOTES'].idxmin(), df['GENERAL\nVOTES'].idxmax()

('A', 906)

In [81]:
df['GENERAL\nVOTES'].idxmin(axis=0)

'A'

In [5]:
df['NAME'].str.split(" ").str.get(0)

0           SOYAM
1           Godam
2          RATHOD
3            NOTA
4        Satyapal
          ...    
2258         Anil
2259    B.B.PATIL
2260        MADAN
2261       BANALA
2262         NOTA
Name: NAME, Length: 2263, dtype: object

In [7]:
df['GENERAL\nVOTES'].apply(np.mean)

0       376892.0
1       318665.0
2       314057.0
3        13030.0
4       644459.0
          ...   
2258     14661.0
2259    434066.0
2260    427900.0
2261    138731.0
2262     11138.0
Name: GENERAL\nVOTES, Length: 2263, dtype: float64

In [9]:
df['GENERAL\nVOTES'].apply(np.cumsum)

0       [376892]
1       [318665]
2       [314057]
3        [13030]
4       [644459]
          ...   
2258     [14661]
2259    [434066]
2260    [427900]
2261    [138731]
2262     [11138]
Name: GENERAL\nVOTES, Length: 2263, dtype: object

In [10]:
df['GENERAL\nVOTES'].apply(np.exp)

0       inf
1       inf
2       inf
3       inf
4       inf
       ... 
2258    inf
2259    inf
2260    inf
2261    inf
2262    inf
Name: GENERAL\nVOTES, Length: 2263, dtype: float64

In [13]:
df.agg(['count','mean'])

STATE  CONSTITUENCY    NAME       WINNER   PARTY  SYMBOL  GENDER  \
count  2263.0        2263.0  2263.0  2263.000000  2263.0  2018.0  2018.0   
mean      NaN           NaN     NaN     0.238179     NaN     NaN     NaN   

       CRIMINAL\nCASES          AGE  CATEGORY  EDUCATION  ASSETS  LIABILITIES  \
count           2018.0  2018.000000    2018.0     2018.0  2018.0       2018.0   
mean               NaN    52.273538       NaN        NaN     NaN          NaN   

       GENERAL\nVOTES  POSTAL\nVOTES   TOTAL\nVOTES  \
count     2263.000000    2263.000000    2263.000000   
mean    261599.083076     990.710561  262589.793637   

       OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
count                            2263.000000   
mean                               15.811412   

       OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
count                                2263.000000    2.263000e+03  
mean                                   23.190525    1.658016e+06

In [16]:
df.reindex(df.index, method='ffill')
ts2.reindex(ts.index, method='bfill')
ts2.reindex(ts.index, method='nearest')

STATE     CONSTITUENCY                   NAME  WINNER PARTY  \
0         Telangana         ADILABAD         SOYAM BAPU RAO       1   BJP   
1         Telangana         ADILABAD           Godam Nagesh       0   TRS   
2         Telangana         ADILABAD          RATHOD RAMESH       0   INC   
3         Telangana         ADILABAD                   NOTA       0  NOTA   
4     Uttar Pradesh             AGRA  Satyapal Singh Baghel       1   BJP   
...             ...              ...                    ...     ...   ...   
2258    Maharashtra  YAVATMAL-WASHIM     Anil Jayram Rathod       0   IND   
2259      Telangana        ZAHIRABAD              B.B.PATIL       1   TRS   
2260      Telangana        ZAHIRABAD        MADAN MOHAN RAO       0   INC   
2261      Telangana        ZAHIRABAD     BANALA LAXMA REDDY       0   BJP   
2262      Telangana        ZAHIRABAD                   NOTA       0  NOTA   

     SYMBOL GENDER CRIMINAL\nCASES   AGE CATEGORY      EDUCATION  \
0     Lotus   MALE              52  52.0       ST      12th Pass   
1       Car   MALE               0  54.0       ST  Post Graduate   
2      Hand   MALE               3  52.0       ST      12th Pass   
3       NaN    NaN             NaN   NaN      NaN            NaN   
4     Lotus   MALE               5  58.0       SC      Doctorate   
...     ...    ...             ...   ...      ...            ...   
2258   SHIP   MALE               0  43.0  GENERAL  Post Graduate   
2259    Car   MALE              18  63.0  GENERAL       Graduate   
2260   Hand   MALE               0  49.0  GENERAL  Post Graduate   
2261  Lotus   MALE               3  47.0  GENERAL      12th Pass   
2262    NaN    NaN             NaN   NaN      NaN            NaN   

                                ASSETS                  LIABILITIES  \
0            Rs 30,99,414\n ~ 30 Lacs+      Rs 2,31,450\n ~ 2 Lacs+   
1          Rs 1,84,77,888\n ~ 1 Crore+      Rs 8,47,000\n ~ 8 Lacs+   
2          Rs 3,64,91,000\n ~ 3 Crore+  Rs 1,53,00,000\n ~ 1 Crore+   
3                                  NaN                          NaN   
4          Rs 7,42,74,036\n ~ 7 Crore+    Rs 86,06,522\n ~ 86 Lacs+   
...                                ...                          ...   
2258         Rs 48,90,000\n ~ 48 Lacs+    Rs 10,20,000\n ~ 10 Lacs+   
2259  Rs 1,28,78,51,556\n ~ 128 Crore+  Rs 1,15,35,000\n ~ 1 Crore+   
2260     Rs 90,36,63,001\n ~ 90 Crore+                     Rs 0\n ~   
2261       Rs 5,85,77,327\n ~ 5 Crore+    Rs 52,50,000\n ~ 52 Lacs+   
2262                               NaN                          NaN   

      GENERAL\nVOTES  POSTAL\nVOTES  TOTAL\nVOTES  \
0             376892            482        377374   
1             318665            149        318814   
2             314057            181        314238   
3              13030              6         13036   
4             644459           2416        646875   
...              ...            ...           ...   
2258           14661             25         14686   
2259          434066            178        434244   
2260          427900            115        428015   
2261          138731            216        138947   
2262           11138              2         11140   

      OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
0                                 25.330684   
1                                 21.399929   
2                                 21.092771   
3                                  0.875023   
4                                 33.383823   
...                                     ...   
2258                               0.766419   
2259                              28.975369   
2260                              28.559732   
2261                               9.271379   
2262                               0.743328   

      OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
0                                     35.468248         1489790  
1                                     29.964370         1489790  
2                  

In [ ]:
df.rename_axis(index={'let': 'abc'})

In [17]:
df.sort_values(by='STATE')

STATE               CONSTITUENCY  \
105  Andaman & Nicobar Islands  ANDAMAN & NICOBAR ISLANDS   
106  Andaman & Nicobar Islands  ANDAMAN & NICOBAR ISLANDS   
107  Andaman & Nicobar Islands  ANDAMAN & NICOBAR ISLANDS   
108  Andaman & Nicobar Islands  ANDAMAN & NICOBAR ISLANDS   
109  Andaman & Nicobar Islands  ANDAMAN & NICOBAR ISLANDS   
..                         ...                        ...   
453                West Bengal                     BOLPUR   
452                West Bengal                     BOLPUR   
446                West Bengal                  BISHNUPUR   
603                West Bengal                 DARJEELING   
444                West Bengal                  BISHNUPUR   

                      NAME  WINNER   PARTY                   SYMBOL GENDER  \
105     KULDEEP RAI SHARMA       1     INC                     Hand   MALE   
106           VISHAL JOLLY       0     BJP                    Lotus   MALE   
107  PARITOSH KUMAR HALDAR       0     IND               Helicopter   MALE   
108         SANJAY MESHACK       0     AAP                    Broom   MALE   
109           PRAKASH MINJ       0     BSP                 Elephant   MALE   
..                     ...     ...     ...                      ...    ...   
453          DAS RAMPRASAD       0     BJP                    Lotus   MALE   
452         ASIT KUMAR MAL       1    AITC        Flowers and Grass   MALE   
446                   NOTA       0    NOTA                      NaN    NaN   
603         Sankar Malakar       0     INC                     Hand   MALE   
444             KHAN SUNIL       0  CPI(M)  Hammer, Sickle and Star   MALE   

    CRIMINAL\nCASES   AGE CATEGORY              EDUCATION  \
105               0  52.0  GENERAL  Graduate Professional   
106               1  46.0  GENERAL  Graduate Professional   
107               0  61.0  GENERAL          Post Graduate   
108               0  49.0  GENERAL              12th Pass   
109               0  43.0       SC          Post Graduate   
..              ...   ...      ...                    ...   
453               0  53.0       SC          Post Graduate   
452               0  63.0       SC              10th Pass   
446             NaN   NaN      NaN                    NaN   
603               2  65.0       SC               Graduate   
444               0  72.0       SC               Graduate   

                            ASSETS                  LIABILITIES  \
105  Rs 13,22,33,012\n ~ 13 Crore+  Rs 8,04,50,870\n ~ 8 Crore+   
106    Rs 8,51,40,573\n ~ 8 Crore+    Rs 46,33,914\n ~ 46 Lacs+   
107    Rs 1,99,16,000\n ~ 1 Crore+    Rs 13,11,000\n ~ 13 Lacs+   
108    Rs 9,98,87,782\n ~ 9 Crore+    Rs 17,91,076\n ~ 17 Lacs+   
109      Rs 12,50,000\n ~ 12 Lacs+      Rs 2,40,000\n ~ 2 Lacs+   
..                             ...                          ...   
453    Rs 1,15,01,067\n ~ 1 Crore+    Rs 49,05,000\n ~ 49 Lacs+   
452      Rs 13,10,691\n ~ 13 Lacs+                     Rs 0\n ~   
446                            NaN                          NaN   
603    Rs 3,65,63,205\n ~ 3 Crore+                     Rs 0\n ~   
444    Rs 2,02,99,997\n ~ 2 Crore+                     Rs 0\n ~   

     GENERAL\nVOTES  POSTAL\nVOTES  TOTAL\nVOTES  \
105           95249             59         95308   
106           93772            129         93901   
107            5339              2          5341   
108            2837              2          2839   
109            2478              8          2486   
..              ...            ...           ...   
453          591445           1324        592769   
452          698441            730        699171   
446           14414             22         14436   
603           64744            442         65186   
444          102498            117        102615   

     OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
105                              29.926744   
106                              29.484945   
107                               1.677076   
108     

In [22]:
x = np.random.randint(low = 0 , high = 10 ,size=(10))

In [23]:
x.searchsorted([0,8])

array([0, 8], dtype=int64)

In [25]:
df['AGE'].nlargest(3)

1855    86.0
2137    86.0
2006    83.0
Name: AGE, dtype: float64

In [27]:
df.nsmallest(5,'AGE')

STATE     CONSTITUENCY              NAME  WINNER PARTY  \
681   Chhattisgarh             DURG  GEETANJALI SINGH       0   BSP   
1132        Odisha         KEONJHAR   Chandrani Murmu       0   BJD   
1502    Tamil Nadu     NAGAPATTINAM         MALATHI P       0   NTK   
1789   West Bengal         RANAGHAT     RUPALI BISWAS       0  AITC   
1848         Bihar  SAMASTIPUR (SC)         Asha Devi       0   AAM   

                 SYMBOL  GENDER CRIMINAL\nCASES   AGE CATEGORY  \
681            Elephant  FEMALE               0  25.0  GENERAL   
1132              Conch  FEMALE               0  25.0       ST   
1502        Ganna Kisan  FEMALE               0  25.0       SC   
1789  Flowers and Grass  FEMALE               0  25.0       SC   
1848     CHAPATI ROLLER  FEMALE               1  25.0       SC   

                  EDUCATION                     ASSETS  \
681           Post Graduate  Rs 54,48,306\n ~ 54 Lacs+   
1132  Graduate Professional    Rs 3,40,580\n ~ 3 Lacs+   
1502  Graduate Professional    Rs 1,19,000\n ~ 1 Lacs+   
1789               Graduate  Rs 73,70,951\n ~ 73 Lacs+   
1848               Literate  Rs 16,28,121\n ~ 16 Lacs+   

                    LIABILITIES  GENERAL\nVOTES  POSTAL\nVOTES  TOTAL\nVOTES  \
681   Rs 29,00,000\n ~ 29 Lacs+           20071             53         20124   
1132                   Rs 0\n ~          525886            473        526359   
1502     Rs 55,400\n ~ 55 Thou+           51207            241         51448   
1789  Rs 17,27,897\n ~ 17 Lacs+          548736           1089        549825   
1848     Rs 51,000\n ~ 51 Thou+           14099             15         14114   

      OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
681                                1.037176   
1132                              34.704501   
1502                               3.946461   
1789                              31.200135   
1848                               0.840604   

      OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
681                                    1.444943         1940269  
1132                                  44.740195         1516688  
1502                                   5.129821         1303649  
1789                                  37.030315         1762252  
1848                                   1.384036         1679030

In [28]:
df.reindex_like(df).fillna(value=0.0)

STATE     CONSTITUENCY                   NAME  WINNER PARTY  \
0         Telangana         ADILABAD         SOYAM BAPU RAO       1   BJP   
1         Telangana         ADILABAD           Godam Nagesh       0   TRS   
2         Telangana         ADILABAD          RATHOD RAMESH       0   INC   
3         Telangana         ADILABAD                   NOTA       0  NOTA   
4     Uttar Pradesh             AGRA  Satyapal Singh Baghel       1   BJP   
...             ...              ...                    ...     ...   ...   
2258    Maharashtra  YAVATMAL-WASHIM     Anil Jayram Rathod       0   IND   
2259      Telangana        ZAHIRABAD              B.B.PATIL       1   TRS   
2260      Telangana        ZAHIRABAD        MADAN MOHAN RAO       0   INC   
2261      Telangana        ZAHIRABAD     BANALA LAXMA REDDY       0   BJP   
2262      Telangana        ZAHIRABAD                   NOTA       0  NOTA   

     SYMBOL GENDER CRIMINAL\nCASES   AGE CATEGORY      EDUCATION  \
0     Lotus   MALE              52  52.0       ST      12th Pass   
1       Car   MALE               0  54.0       ST  Post Graduate   
2      Hand   MALE               3  52.0       ST      12th Pass   
3       NaN    NaN             NaN   NaN      NaN            NaN   
4     Lotus   MALE               5  58.0       SC      Doctorate   
...     ...    ...             ...   ...      ...            ...   
2258   SHIP   MALE               0  43.0  GENERAL  Post Graduate   
2259    Car   MALE              18  63.0  GENERAL       Graduate   
2260   Hand   MALE               0  49.0  GENERAL  Post Graduate   
2261  Lotus   MALE               3  47.0  GENERAL      12th Pass   
2262    NaN    NaN             NaN   NaN      NaN            NaN   

                                ASSETS                  LIABILITIES  \
0            Rs 30,99,414\n ~ 30 Lacs+      Rs 2,31,450\n ~ 2 Lacs+   
1          Rs 1,84,77,888\n ~ 1 Crore+      Rs 8,47,000\n ~ 8 Lacs+   
2          Rs 3,64,91,000\n ~ 3 Crore+  Rs 1,53,00,000\n ~ 1 Crore+   
3                                  NaN                          NaN   
4          Rs 7,42,74,036\n ~ 7 Crore+    Rs 86,06,522\n ~ 86 Lacs+   
...                                ...                          ...   
2258         Rs 48,90,000\n ~ 48 Lacs+    Rs 10,20,000\n ~ 10 Lacs+   
2259  Rs 1,28,78,51,556\n ~ 128 Crore+  Rs 1,15,35,000\n ~ 1 Crore+   
2260     Rs 90,36,63,001\n ~ 90 Crore+                     Rs 0\n ~   
2261       Rs 5,85,77,327\n ~ 5 Crore+    Rs 52,50,000\n ~ 52 Lacs+   
2262                               NaN                          NaN   

      GENERAL\nVOTES  POSTAL\nVOTES  TOTAL\nVOTES  \
0             376892            482        377374   
1             318665            149        318814   
2             314057            181        314238   
3              13030              6         13036   
4             644459           2416        646875   
...              ...            ...           ...   
2258           14661             25         14686   
2259          434066            178        434244   
2260          427900            115        428015   
2261          138731            216        138947   
2262           11138              2         11140   

      OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
0                                 25.330684   
1                                 21.399929   
2                                 21.092771   
3                                  0.875023   
4                                 33.383823   
...                                     ...   
2258                               0.766419   
2259                              28.975369   
2260                              28.559732   
2261                               9.271379   
2262                               0.743328   

      OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
0                                     35.468248         1489790  
1                                     29.964370         1489790  
2                  

In [29]:
pd.date_range('20130101', periods=3)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03'], dtype='datetime64[ns]', freq='D')

In [32]:
df.select_dtypes(include=['float64'])

AGE  OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
0     52.0                              25.330684   
1     54.0                              21.399929   
2     52.0                              21.092771   
3      NaN                               0.875023   
4     58.0                              33.383823   
...    ...                                    ...   
2258  43.0                               0.766419   
2259  63.0                              28.975369   
2260  49.0                              28.559732   
2261  47.0                               9.271379   
2262   NaN                               0.743328   

      OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  
0                                     35.468248  
1                                     29.964370  
2                                     29.534285  
3                                      1.225214  
4                                     56.464615  
...                                         ...  
2258                                   1.250060  
2259                                  41.574183  
2260                                  40.977823  
2261                                  13.302678  
2262                                   1.066535  

[2263 rows x 3 columns]

In [64]:
#pip install mysql-connector

In [37]:
import mysql.connector

In [65]:
mydb = mysql.connector.connect(host = 'localhost',user = 'root',passwd = '1234')

In [66]:
mycursor=mydb.cursor()

In [67]:
mycursor.execute("show databases")

In [68]:
for db in mycursor:
    print(db)

('information_schema',)
('mysql',)
('performance_schema',)
('sakila',)
('sys',)
('world',)


In [69]:
query = ("select * from sakila.orders_superstore limit 10")

In [70]:
mycursor.execute(query)

In [81]:
mycursor.description

[('Row_ID', 3, None, None, None, None, 0, 53251),
 ('Order_ID', 253, None, None, None, None, 1, 0),
 ('Order_Date', 10, None, None, None, None, 1, 128),
 ('Ship_Date', 10, None, None, None, None, 1, 128),
 ('Ship_Mode', 253, None, None, None, None, 1, 0),
 ('Customer_ID', 253, None, None, None, None, 1, 0),
 ('Customer_Name', 253, None, None, None, None, 1, 0),
 ('Segment', 253, None, None, None, None, 1, 0),
 ('Country', 253, None, None, None, None, 1, 0),
 ('City', 253, None, None, None, None, 1, 0),
 ('State', 253, None, None, None, None, 1, 0),
 ('Postal_Code', 3, None, None, None, None, 0, 53257),
 ('Region', 253, None, None, None, None, 1, 0),
 ('Product_ID', 253, None, None, None, None, 1, 0),
 ('Category', 253, None, None, None, None, 1, 0),
 ('Sub-Category', 253, None, None, None, None, 1, 0),
 ('Product_Name', 253, None, None, None, None, 1, 0),
 ('Sales', 246, None, None, None, None, 1, 32768),
 ('Quantity', 3, None, None, None, None, 0, 53257),
 ('Discount', 246, None, None

In [80]:
mycursor.column_names

('Row_ID',
 'Order_ID',
 'Order_Date',
 'Ship_Date',
 'Ship_Mode',
 'Customer_ID',
 'Customer_Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal_Code',
 'Region',
 'Product_ID',
 'Category',
 'Sub-Category',
 'Product_Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit')

In [58]:
table_rows = mycursor.fetchall()

In [63]:
mycursor.close()
mydb.close()

In [59]:
table_rows

[(1,
  'CA-2016-152156',
  datetime.date(2016, 11, 8),
  datetime.date(2016, 11, 11),
  'Second Class',
  'CG-12520',
  'Claire Gute',
  'Consumer',
  'United States',
  'Henderson',
  'Kentucky',
  42420,
  'South',
  'FUR-BO-10001798',
  'Furniture',
  'Bookcases',
  'Bush Somerset Collection Bookcase',
  Decimal('261.960000000000000000000000000000'),
  2,
  Decimal('0.00'),
  Decimal('41.913600000000000000000000000000')),
 (2,
  'CA-2016-152156',
  datetime.date(2016, 11, 8),
  datetime.date(2016, 11, 11),
  'Second Class',
  'CG-12520',
  'Claire Gute',
  'Consumer',
  'United States',
  'Henderson',
  'Kentucky',
  42420,
  'South',
  'FUR-CH-10000454',
  'Furniture',
  'Chairs',
  'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
  Decimal('731.940000000000000000000000000000'),
  3,
  Decimal('0.00'),
  Decimal('219.582000000000000000000000000000')),
 (3,
  'CA-2016-138688',
  datetime.date(2016, 6, 12),
  datetime.date(2016, 6, 16),
  'Second Class',
  'DV-13045',
 

In [60]:
pd.DataFrame(table_rows)

0               1           2           3               4         5   \
0   1  CA-2016-152156  2016-11-08  2016-11-11    Second Class  CG-12520   
1   2  CA-2016-152156  2016-11-08  2016-11-11    Second Class  CG-12520   
2   3  CA-2016-138688  2016-06-12  2016-06-16    Second Class  DV-13045   
3   4  US-2015-108966  2015-10-11  2015-10-18  Standard Class  SO-20335   
4   5  US-2015-108966  2015-10-11  2015-10-18  Standard Class  SO-20335   
5   6  CA-2014-115812  2014-06-09  2014-06-14  Standard Class  BH-11710   
6   7  CA-2014-115812  2014-06-09  2014-06-14  Standard Class  BH-11710   
7   8  CA-2014-115812  2014-06-09  2014-06-14  Standard Class  BH-11710   
8   9  CA-2014-115812  2014-06-09  2014-06-14  Standard Class  BH-11710   
9  10  CA-2014-115812  2014-06-09  2014-06-14  Standard Class  BH-11710   

                6          7              8                9   ...     11  \
0      Claire Gute   Consumer  United States        Henderson  ...  42420   
1      Claire Gute   Consumer  United States        Henderson  ...  42420   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...  90036   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...  33311   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...  33311   
5  Brosina Hoffman   Consumer  United States      Los Angeles  ...  90032   
6  Brosina Hoffman   Consumer  United States      Los Angeles  ...  90032   
7  Brosina Hoffman   Consumer  United States      Los Angeles  ...  90032   
8  Brosina Hoffman   Consumer  United States      Los Angeles  ...  90032   
9  Brosina Hoffman   Consumer  United States      Los Angeles  ...  90032   

      12               13               14           15  \
0  South  FUR-BO-10001798        Furniture    Bookcases   
1  South  FUR-CH-10000454        Furniture       Chairs   
2   West  OFF-LA-10000240  Office Supplies       Labels   
3  South  FUR-TA-10000577        Furniture       Tables   
4  South  OFF-ST-10000760  Office Supplies      Storage   
5   West  FUR-FU-10001487        Furniture  Furnishings   
6   West  OFF-AR-10002833  Office Supplies          Art   
7   West  TEC-PH-10002275       Technology       Phones   
8   West  OFF-BI-10003910  Office Supplies      Binders   
9   West  OFF-AP-10002892  Office Supplies   Appliances   

                                                  16  \
0                  Bush Somerset Collection Bookcase   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...   
2  Self-Adhesive Address Labels for Typewriters b...   
3      Bretford CR4500 Series Slim Rectangular Table   
4                     Eldon Fold 'N Roll Cart System   
5  Eldon Expressions Wood and Plastic Desk Access...   
6                                         Newell 322   
7                     Mitel 5320 IP Phone VoIP phone   
8  DXL Angle-View Binders with Locking Rings by S...   
9                   Belkin F5C206VTEL 6 Outlet Surge   

                                   17 18    19  \
0  261.960000000000000000000000000000  2  0.00   
1  731.940000000000000000000000000000  3  0.00   
2   14.620000000000000000000000000000  2  0.00   
3  957.577500000000000000000000000000  5  0.45   
4   22.368000000000000000000000000000  2  0.20   
5   48.860000000000000000000000000000  7  0.00   
6    7.280000000000000000000000000000  4  0.00   
7  907.152000000000000000000000000000  6  0.20   
8   18.504000000000000000000000000000  3  0.20   
9  114.900000000000000000000000000000  5  0.00   

                                    20  
0    41.913600000000000000000000000000  
1   219.582000000000000000000000000000  
2     6.871400000000000000000000000000  
3  -383.031000000000000000000000000000  
4     2.516400000000000000000000000000  
5    14.169400000000000000000000000000  
6     1.965600000000000000000000000000  
7    90.715200000000000000000000000000  
8     5.782500000000000000000000000000  
9    34.470000000000000000000000000000  

[10 rows x 21 columns]

In [48]:
pd.read_csv('path_to_file.csv', na_values=[5])
#In the example above 5 and 5.0 will be recognized as NaN, in addition to the defaults. A string will first be interpreted as a numerical 5, then as a NaN.

CMySQLCursor: select * from sakila.orders_superstore l..


In [96]:
from io import StringIO

In [93]:
data = 'a,b,c~1,2,3~4,5,6'

In [98]:
pd.read_csv(StringIO(data), lineterminator='~')

a  b  c
0  1  2  3
1  4  5  6

In [ ]:
df = pd.read_excel(xlsx, 'Sheet1')

In [ ]:
with pd.ExcelFile('path_to_file.xls') as xls:
    data['Sheet1'] = pd.read_excel(xls, 'Sheet1', index_col=None,na_values=['NA'])
    data['Sheet2'] = pd.read_excel(xls, 'Sheet2', index_col=1)

# Numpy

In [1]:
import numpy as np

In [115]:
a = np.floor(10*np.random.random((2,2)))
b= np.floor(15*np.random.random((2,2)))

In [127]:
x=np.vstack((a,b))
#np.hstack((a,b))

In [119]:
np.c_[a,b] # same as hstack

array([[ 7.,  4., 14., 12.],
       [ 0.,  8., 12.,  5.]])

In [122]:
np.arange(12).reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [123]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.floor(10*np.random.random((2,12)))

In [129]:
x

array([[ 7.,  4.],
       [ 0.,  8.],
       [14., 12.],
       [12.,  5.]])

In [130]:
x.cumsum(axis=0)

array([[ 7.,  4.],
       [ 7., 12.],
       [21., 24.],
       [33., 29.]])

In [134]:
print(x.flatten())

[ 7.  4.  0.  8. 14. 12. 12.  5.]


In [143]:
z= np.random.randint(low = 1,high = 6,size=(2,12))

In [145]:
z

array([[2, 5, 4, 2, 2, 2, 4, 5, 2, 5, 3, 2],
       [1, 2, 3, 2, 2, 5, 1, 1, 2, 5, 3, 4]])

In [147]:
np.vsplit(z,2)

[array([[2, 5, 4, 2, 2, 2, 4, 5, 2, 5, 3, 2]]),
 array([[1, 2, 3, 2, 2, 5, 1, 1, 2, 5, 3, 4]])]

In [148]:
np.hsplit(z,3)

[array([[2, 5, 4, 2],
        [1, 2, 3, 2]]),
 array([[2, 2, 4, 5],
        [2, 5, 1, 1]]),
 array([[2, 5, 3, 2],
        [2, 5, 3, 4]])]

In [157]:
np.arange(1,10,3)

array([1, 4, 7])

In [158]:
a.transpose()

array([[7., 0.],
       [4., 8.]])

In [2]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [3]:
x=np.random.randint(2,5,(4,4))

In [6]:
x.dtype

dtype('int32')

In [7]:
x.astype('float')

array([[3., 3., 3., 3.],
       [2., 2., 3., 3.],
       [3., 2., 2., 4.],
       [2., 3., 2., 4.]])

In [9]:
(x.astype('float32')).dtype

dtype('float32')

In [11]:
x = np.arange(4)
z = np.ones((3,4))

In [13]:
x,z

(array([0, 1, 2, 3]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [12]:
x+z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [18]:
def square(x):
    return x * x

In [19]:
df.head()

STATE CONSTITUENCY                   NAME  WINNER PARTY SYMBOL  \
0      Telangana     ADILABAD         SOYAM BAPU RAO       1   BJP  Lotus   
1      Telangana     ADILABAD           Godam Nagesh       0   TRS    Car   
2      Telangana     ADILABAD          RATHOD RAMESH       0   INC   Hand   
3      Telangana     ADILABAD                   NOTA       0  NOTA    NaN   
4  Uttar Pradesh         AGRA  Satyapal Singh Baghel       1   BJP  Lotus   

  GENDER CRIMINAL\nCASES   AGE CATEGORY      EDUCATION  \
0   MALE              52  52.0       ST      12th Pass   
1   MALE               0  54.0       ST  Post Graduate   
2   MALE               3  52.0       ST      12th Pass   
3    NaN             NaN   NaN      NaN            NaN   
4   MALE               5  58.0       SC      Doctorate   

                        ASSETS                  LIABILITIES  GENERAL\nVOTES  \
0    Rs 30,99,414\n ~ 30 Lacs+      Rs 2,31,450\n ~ 2 Lacs+          376892   
1  Rs 1,84,77,888\n ~ 1 Crore+      Rs 8,47,000\n ~ 8 Lacs+          318665   
2  Rs 3,64,91,000\n ~ 3 Crore+  Rs 1,53,00,000\n ~ 1 Crore+          314057   
3                          NaN                          NaN           13030   
4  Rs 7,42,74,036\n ~ 7 Crore+    Rs 86,06,522\n ~ 86 Lacs+          644459   

   POSTAL\nVOTES  TOTAL\nVOTES  OVER TOTAL ELECTORS \nIN CONSTITUENCY  \
0            482        377374                              25.330684   
1            149        318814                              21.399929   
2            181        314238                              21.092771   
3              6         13036                               0.875023   
4           2416        646875                              33.383823   

   OVER TOTAL VOTES POLLED \nIN CONSTITUENCY  TOTAL ELECTORS  
0                                  35.468248         1489790  
1                                  29.964370         1489790  
2                                  29.534285         1489790  
3                                   1.225214         1489790  
4                                  56.464615         1937690

In [21]:
df['AGE'].apply(square)

0       2704.0
1       2916.0
2       2704.0
3          NaN
4       3364.0
         ...  
2258    1849.0
2259    3969.0
2260    2401.0
2261    2209.0
2262       NaN
Name: AGE, Length: 2263, dtype: float64

In [22]:
df['AGE'].apply(lambda x: x * x)

0       2704.0
1       2916.0
2       2704.0
3          NaN
4       3364.0
         ...  
2258    1849.0
2259    3969.0
2260    2401.0
2261    2209.0
2262       NaN
Name: AGE, Length: 2263, dtype: float64

In [23]:
(lambda x: x + 1)(9)

10

In [24]:
>>> add_one = lambda x: x + 1
>>> add_one(2)

3

In [25]:
def add_one(x):
    return x + 1

In [27]:
(lambda x, y: x + y)(4,6)

10

In [28]:
high_ord_func = lambda x, func: x + func(x)

In [32]:
high_ord_func(2, lambda x: x * x)

6

In [33]:
>>> (lambda x:
     (x % 2 and 'odd' or 'even'))(3)

'odd'

In [40]:
>>> list(map(lambda x: x.upper(), ['cat', 'dog', 'cow']))

['CAT', 'DOG', 'COW']

In [41]:
list(filter(lambda x: 'o' in x, ['cat', 'dog', 'cow']))

['dog', 'cow']

In [42]:
>>> ids = ['id1', 'id2', 'id30', 'id3', 'id22', 'id100']
>>> print(sorted(ids)) # Lexicographic sort

['id1', 'id100', 'id2', 'id22', 'id3', 'id30']


In [50]:
(lambda x: int(x[2:]))('id100')

100

In [43]:
sorted(ids, key=lambda x: int(x[2:])) # Integer sort

['id1', 'id2', 'id3', 'id22', 'id30', 'id100']

In [67]:
for i in df.columns:
    new_col = re.sub('\n',"_",i)
    df.rename(columns={i:new_col},inplace=True)

In [69]:
map(lambda x: df[x],)

STATE     CONSTITUENCY                   NAME  WINNER PARTY  \
0         Telangana         ADILABAD         SOYAM BAPU RAO       1   BJP   
1         Telangana         ADILABAD           Godam Nagesh       0   TRS   
2         Telangana         ADILABAD          RATHOD RAMESH       0   INC   
3         Telangana         ADILABAD                   NOTA       0  NOTA   
4     Uttar Pradesh             AGRA  Satyapal Singh Baghel       1   BJP   
...             ...              ...                    ...     ...   ...   
2258    Maharashtra  YAVATMAL-WASHIM     Anil Jayram Rathod       0   IND   
2259      Telangana        ZAHIRABAD              B.B.PATIL       1   TRS   
2260      Telangana        ZAHIRABAD        MADAN MOHAN RAO       0   INC   
2261      Telangana        ZAHIRABAD     BANALA LAXMA REDDY       0   BJP   
2262      Telangana        ZAHIRABAD                   NOTA       0  NOTA   

     SYMBOL GENDER CRIMINAL_CASES   AGE CATEGORY      EDUCATION  \
0     Lotus   MALE             52  52.0       ST      12th Pass   
1       Car   MALE              0  54.0       ST  Post Graduate   
2      Hand   MALE              3  52.0       ST      12th Pass   
3       NaN    NaN            NaN   NaN      NaN            NaN   
4     Lotus   MALE              5  58.0       SC      Doctorate   
...     ...    ...            ...   ...      ...            ...   
2258   SHIP   MALE              0  43.0  GENERAL  Post Graduate   
2259    Car   MALE             18  63.0  GENERAL       Graduate   
2260   Hand   MALE              0  49.0  GENERAL  Post Graduate   
2261  Lotus   MALE              3  47.0  GENERAL      12th Pass   
2262    NaN    NaN            NaN   NaN      NaN            NaN   

                                ASSETS                  LIABILITIES  \
0            Rs 30,99,414\n ~ 30 Lacs+      Rs 2,31,450\n ~ 2 Lacs+   
1          Rs 1,84,77,888\n ~ 1 Crore+      Rs 8,47,000\n ~ 8 Lacs+   
2          Rs 3,64,91,000\n ~ 3 Crore+  Rs 1,53,00,000\n ~ 1 Crore+   
3                                  NaN                          NaN   
4          Rs 7,42,74,036\n ~ 7 Crore+    Rs 86,06,522\n ~ 86 Lacs+   
...                                ...                          ...   
2258         Rs 48,90,000\n ~ 48 Lacs+    Rs 10,20,000\n ~ 10 Lacs+   
2259  Rs 1,28,78,51,556\n ~ 128 Crore+  Rs 1,15,35,000\n ~ 1 Crore+   
2260     Rs 90,36,63,001\n ~ 90 Crore+                     Rs 0\n ~   
2261       Rs 5,85,77,327\n ~ 5 Crore+    Rs 52,50,000\n ~ 52 Lacs+   
2262                               NaN                          NaN   

      GENERAL_VOTES  POSTAL_VOTES  TOTAL_VOTES  \
0            376892           482       377374   
1            318665           149       318814   
2            314057           181       314238   
3             13030             6        13036   
4            644459          2416       646875   
...             ...           ...          ...   
2258          14661            25        14686   
2259         434066           178       434244   
2260         427900           115       428015   
2261         138731           216       138947   
2262          11138             2        11140   

      OVER TOTAL ELECTORS _IN CONSTITUENCY  \
0                                25.330684   
1                                21.399929   
2                                21.092771   
3                                 0.875023   
4                                33.383823   
...                                    ...   
2258                              0.766419   
2259                             28.975369   
2260                             28.559732   
2261                              9.271379   
2262                              0.743328   

      OVER TOTAL VOTES POLLED _IN CONSTITUENCY  TOTAL ELECTORS  
0                                    35.468248         1489790  
1                                    29.964370         1489790  
2                                    29.534285         1489790  
3                

In [3]:
pwd()

'C:\\Users\\Raushan Kumar\\Downloads\\Code'

In [1]:
from openpyxl import Workbook
import time

In [2]:
book = Workbook()
sheet = book.active

In [10]:
time.strftime("%x-%X")

'10/13/20-23:00:21'

In [14]:
for i in range(1,100):
    sheet['A'+str(i)]=56
book.save("sample.xlsx")

In [4]:
sheet['A1'] = 56
sheet['A2'] = 43

now = time.strftime("%x")
sheet['A3'] = now

book.save("sample.xlsx")