Python has several built-in data types, including:

- Numeric types: `int`, `float`, `complex`
- Sequence types: `list`, `tuple`, `range`
- Text type: `str`
- Mapping type: `dict`
- Set types: `set`, `frozenset`
- Boolean type: `bool`
- Binary types: `bytes`, `bytearray`, `memoryview`

Each data type has its own set of operations and methods that can be used to manipulate and work with the data.

In Python, variables can be classified into different types based on the scope and lifetime of the variable. Here are the main types of variables in Python:

- Local variables: These are variables that are defined inside a function and have a local scope. They are created when the function is called and destroyed when the function returns.
- Global variables: These are variables that are defined outside of any function and have a global scope. They can be accessed from any part of the program.
- Instance variables: These are variables that are defined inside a class and belong to an instance of the class. They are created when an object is created and destroyed when the object is destroyed.
- Class variables: These are variables that are defined inside a class and belong to the class itself. They are shared by all instances of the class.

Each type of variable has its own rules and best practices for usage.

In Python, there are certain reserved words that have special meanings and cannot be used as variable names. These reserved words are also known as keywords. Here is a list of all the keywords in Python:

You should avoid using these keywords as variable names in your code, as doing so can cause syntax errors or unexpected behavior.

**False, None, True, and, as, assert, async, await, break, class, continue, def, del, elif, else, except, finally, for, from, global, if, import, in, is, lambda, nonlocal, not, or, pass, raise, return, try, while, with, yield**

In Python, indentation is used to define the scope and hierarchy of code blocks. Indentation refers to the number of spaces or tabs at the beginning of a line of code. 

Here's an example of how indentation is used in Python:



In [ ]:
if x > 0:
    print("x is positive")
else:
    print("x is zero or negative")

In Python, data types can be classified as either mutable or immutable. 

Immutable data types are those that cannot be changed once they are created. Examples of immutable data types in Python include `int`, `float`, `bool`, `str`, and `tuple`. If you try to modify an immutable object, Python will create a new object instead of modifying the existing one.

Mutable data types are those that can be changed after they are created. Examples of mutable data types in Python include `list`, `dict`, and `set`. If you modify a mutable object, Python will modify the existing object instead of creating a new one.

Here's an example to illustrate the difference between mutable and immutable data types:



In [ ]:
# Immutable data type (int)
x = 5
y = x
x = x + 1
print(x)  # Output: 6
print(y)  # Output: 5

# Mutable data type (list)
a = [1, 2, 3]
b = a
a.append(4)
print(a)  # Output: [1, 2, 3, 4]
print(b)  # Output: [1, 2, 3, 4]

### Lists
Lists are ordered, mutable collections of objects. They are defined using square brackets `[]` and elements are separated by commas.



In [ ]:
# Creating a list
my_list = [1, 2, 3, 4, 5]

# Accessing elements of a list
print(my_list[0])  # Output: 1
print(my_list[-1])  # Output: 5

# Slicing a list
print(my_list[1:3])  # Output: [2, 3]

# Modifying elements of a list
my_list[0] = 0
print(my_list)  # Output: [0, 2, 3, 4, 5]

# Appending an element to a list
my_list.append(6)
print(my_list)  # Output: [0, 2, 3, 4, 5, 6]

# Extending a list with another list
my_list.extend([7, 8, 9])
print(my_list)  # Output: [0, 2, 3, 4, 5, 6, 7, 8, 9]

# Inserting an element at a specific index
my_list.insert(1, 1)
print(my_list)  # Output: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Removing an element from a list
my_list.remove(0)
print(my_list)  # Output: [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Popping an element from a list
popped_element = my_list.pop()
print(popped_element)  # Output: 9
print(my_list)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]

# Checking if an element is in a list
if 5 in my_list:
    print("5 is in the list")

# Sorting a list
my_list.sort()
print(my_list)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]

# Reversing a list
my_list.reverse()
print(my_list)  # Output: [8, 7, 6, 5, 4, 3, 2, 1]



### Tuples
Tuples are ordered, immutable collections of objects. They are defined using parentheses `()` and elements are separated by commas.



In [ ]:
# Creating a tuple
my_tuple = (1, 2, 3, 4, 5)

# Accessing elements of a tuple
print(my_tuple[0])  # Output: 1
print(my_tuple[-1])  # Output: 5

# Slicing a tuple
print(my_tuple[1:3])  # Output: (2, 3)

# Concatenating tuples
my_tuple2 = (6, 7, 8)
concatenated_tuple = my_tuple + my_tuple2
print(concatenated_tuple)  # Output: (1, 2, 3, 4, 5, 6, 7, 8)

# Repeating a tuple
repeated_tuple = my_tuple * 2
print(repeated_tuple)  # Output: (1, 2, 3, 4, 5, 1, 2, 3, 4, 5)

# Converting a tuple to a list
my_list = list(my_tuple)
print(my_list)  # Output: [1, 2, 3, 4, 5]

# Checking if an element is in a tuple
if 5 in my_tuple:
    print("5 is in the tuple")
    
# Getting the length of a tuple
print(len(my_tuple))  # Output: 5



### Sets
Sets are unordered, mutable collections of unique objects. They are defined using curly braces `{}` or the `set()` function.



In [ ]:
# Define a set of integers
my_set = {1, 2, 3, 4, 5}

# Define a set of strings
fruits = {"apple", "banana", "cherry", "date"}

# Add an element to the set
fruits.add("elderberry")

# Remove an element from the set
fruits.remove("cherry")

To install a package using pip, you can use the following command in your terminal or command prompt:



In [ ]:
pip install package_name



Replace `package_name` with the name of the package you want to install. For example, to install the `numpy` package, you would run:



In [ ]:
pip install numpy

# Set in Python

In [2]:
# Let's take an example to understand
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

# Union of two sets
union_set = set1.union(set2)
print("Union of set1 and set2:", union_set)

# Intersection of two sets
intersection_set = set1.intersection(set2)
print("Intersection of set1 and set2:", intersection_set)

# Difference of two sets
difference_set = set1.difference(set2)
print("Difference of set1 and set2:", difference_set)

# Symmetric difference of two sets
symmetric_difference_set = set1.symmetric_difference(set2)
print("Symmetric difference of set1 and set2:", symmetric_difference_set)

# Subset check
subset_check = set1.issubset(set2)
print("Is set1 a subset of set2?", subset_check)

# Superset check
superset_check = set1.issuperset(set2)
print("Is set1 a superset of set2?", superset_check)

Union of set1 and set2: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection of set1 and set2: {4, 5}
Difference of set1 and set2: {1, 2, 3}
Symmetric difference of set1 and set2: {1, 2, 3, 6, 7, 8}
Is set1 a subset of set2? False
Is set1 a superset of set2? False


# Important Boolean Operator

In [4]:
# AND operator
x = 5
y = 10
z = 15
print(x < y and y < z)

# OR operator
x = 5
y = 10
z = 15
print(x > y or y < z)

# NOT operator
x = True
print(not x)

True
True
False


<h1 align='center'> Array</h1>

*  NumPy’s array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:
    - `ndarray.ndim:` The number of axes(dimensions) of the array.
    - `ndarray.shape:` The dimension of array.For a matrix with x rows and y columns, shape will be (x,y).
    - `ndarray.size:` The total number of elements of the array or It is equal to the product of the elements of the `shape`.
    - `ndarray.dtype:` The type of the elements in the array. Additionally NumPy provides types of its own like- numpy.int32, numpy.int16, and numpy.float64.
    - `ndarray.itemsize:` The size in bytes of each element of the array. 
    - `ndarray.data:` The buffer containing the actual elements of the array. 

## Creating a NumPy array

In [6]:
# ! pip install numpy
import numpy as np

<font color='cadetblue' size='4'>Basic ndarray</font>


In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
# We can specify the type of data inside the array:
print(np.array([1,2,3,4],dtype=np.float32))
# a multi dimension array
print(np.array([[1,2,3,4],[5,6,7,8]]))


[1. 2. 3. 4.]
[[1 2 3 4]
 [5 6 7 8]]


In [15]:
# array of zeros
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<font color='cadetblue' size='4'>Array of Ones</font>


In [13]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

<font color='cadetblue' size='4'>Random number in array</font>

In [16]:
# random 
np.random.rand(2,3)

array([[0.04186302, 0.52639282, 0.62252789],
       [0.88094792, 0.65364788, 0.66506996]])

In [17]:
# An array of the choice
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

<font color='cadetblue' size='4'>Evenly spaced ndarray</font>

In [18]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Another similar function is `np.linspace()`, but instead of step size, it takes in the number of samples that need to be retrieved from the interval. A point to note here is that the last number is included in the values returned unlike in the case of `np.arange()`.**

In [19]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
# generates unity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h1 align='center'>The Shape and Reshaping of NumPy Arrays</h1>

In [26]:
a = np.array([[5,10,15],[20,25,20]])
print('Array:','\n',a)
print('Dimension of the array:','\n',a.ndim)

Array: 
 [[ 5 10 15]
 [20 25 20]]
Dimension of the array: 
 2


In [27]:
a = np.arange(6).reshape(2,3)
print('Array:','\n',a)
print('Shape of the array:','\n',a.shape)
print('Number of rows = ',a.shape[0])
print('Number of columns = ',a.shape[1])
print('Size of array :',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])

Array: 
 [[0 1 2]
 [3 4 5]]
Shape of the array: 
 (2, 3)
Number of rows =  2
Number of columns =  3
Size of array : 6
Manual determination of size of array : 6


<font color='cadetblue' size='4'>Reshaping a NumPy array</font>

In [28]:
# reshape
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [29]:
# -1 makes whatever rows/column possible 
a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,-1)))
print('Three columns :','\n',np.reshape(a,(-1,3)))

Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three columns : 
 [[ 3  6  9]
 [12 18 24]]


<font color='cadetblue' size='4'>Flattening a NumPy array</font>

In [ ]:
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

In [ ]:
b[0] = 0
print(a)

**In this case, the change made was not reflected in the original array.**

In [ ]:
c[0] = 0
print(a)

**But here, the changed value is also reflected in the original ndarray.**

What is happening here is that `flatten()` creates a ***Deep copy*** of the ndarray while `ravel()` creates a ***Shallow copy*** of the ndarray.

> Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing to this memory location. Therefore, any changes made here will not be reflected in the original ndarray.

> A Shallow copy, on the other hand, returns a reference to the original memory location. Meaning the object returned by ravel() is pointing to the same memory location as the original ndarray object. So, definitely, any changes made to this ndarray will also be reflected in the original ndarray too.

<h1 align='center'>Maths with NumPy arrays<h1>

In [ ]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)

In [ ]:
#Addition
add = data+ones
print('Addition of two array','\n',add)

![](https://raw.githubusercontent.com/divyanshugit/Insights-of-Python-Libraries/master/src/img_8.png)

In [ ]:
#Subtraction:
sub = data - ones
print('Subraction of two array:','\n',sub)

#Multiplication:
multi = data*data
print('Multiplication of two array','\n',multi)

#Division:
div = data/data
print('Division by a constant','\n',div)

<font color='cadetblue' size='4'>Mean, Median and Standard deviation</font>

In [ ]:
a = np.arange(5,15,2)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

<font color='cadetblue' size='4'>Min-Max values and their indexes</font>

In [ ]:
a = np.array([[1,6], [4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

In [ ]:
a = np.array([[1,6,5],
[4,3,7]])
# minimum along a column
print('Min :',np.argmin(a,axis=0))
# maximum along a row
print('Max :',np.argmax(a,axis=1))

<h1 align='center'>Sorting in NumPy arrays</h1>

In [ ]:
a = np.array([1,4,2,5,3,6,8,7,9])
print('Sorted array:','\n',np.sort(a, kind='quicksort'))

b = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the column
print('Sort along column :','\n',np.sort(b, kind='mergresort',axis=1))
# sort along the row
print('Sort along row :','\n',np.sort(b, kind='mergresort',axis=0))

<h1 align='center'>Indexing and Slicing of NumPy array</h1>

<font color='cadetblue' size='4'>Slicing 1-D NumPy arrays</font>

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a[1:5])

![](https://raw.githubusercontent.com/divyanshugit/Insights-of-Python-Libraries/master/src/img_1.png)

In [ ]:
print(a[:6:2])
print(a[1::2])
print(a[1:6:])

![](https://raw.githubusercontent.com/divyanshugit/Insights-of-Python-Libraries/master/src/img_2.png)

<font color='cadetblue' size='4'>Slicing 2-D NumPy arrays</font>

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
# print first row values
print('First row values :','\n',a[0:1,:])
# with step-size for columns
print('Alternate values from first row:','\n',a[0:1,::2])
# 
print('Second column values :','\n',a[:,1::2])
print('Arbitrary values :','\n',a[0:1,1:3])

<font color='cadetblue' size='4'>Slicing 3-D NumPy arrays</font>

**So far we haven’t seen a 3-D array. Let’s first visualize how a 3-D array looks like:**

In [ ]:
a = np.array([[[1,2],[3,4],[5,6]],# first axis array
    [[7,8],[9,10],[11,12]],# second axis array
    [[13,14],[15,16],[17,18]]])# third axis array
# 3-D array
print(a)

In [ ]:
print('First array, first row, first column value :','\n',a[0,0,0])
print('First array last column :','\n',a[0,:,1])
print('First two rows for second and third arrays :','\n',a[1:,0:2,0:2])

**If in case you wanted the values as a single dimension array, you can always use the flatten() method to do the job!**

In [ ]:
print('Printing as a single array :','\n',a[1:,0:2,0:2].flatten())

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import misc
import cv2

# read image
img = cv2.imread('../input/dog-images/dog.jpg')
img

In [ ]:
plt.imshow(img)
print(img.shape)

In [ ]:
# flip
plt.imshow(np.flip(img, axis=1))

In [ ]:
img_array = img / 255
img_array.max(), img_array.min()

In [ ]:
img_array.dtype

In [ ]:
img_gray = img_array @ [0.2126, 0.7152, 0.0722]

In [ ]:
img_gray.shape

In [ ]:
plt.imshow(img_gray,  cmap="gray")