In [4]:
import pandas as pd
import numpy as np

In [158]:
m = 100
X = 6 * np.random.rand(m, 1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

In [3]:
from sklearn.svm import LinearSVR
svm_reg = LinearSVR(epsilon=1.5)
svm_reg.fit(X, y)

C:\Users\Raushan Kumar\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LinearSVR(epsilon=1.5)

In [4]:
from sklearn.svm import SVR
svm_poly_reg = SVR(kernel="poly", degree=2, C=100, epsilon=0.1)
svm_poly_reg.fit(X, y)

C:\Users\Raushan Kumar\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR(C=100, degree=2, kernel='poly')

In [15]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
iris = load_iris()
X = iris.data[:, 2:] # petal length and width
y = iris.target
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [22]:
tree_clf.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 2,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': 'deprecated',
 'random_state': None,
 'splitter': 'best'}

In [27]:
from sklearn.tree import export_graphviz
export_graphviz(
tree_clf,
out_file="C:\\Users\\Raushan Kumar\\Downloads\\Code\\iris_tree.png",
feature_names=iris.feature_names[2:],
class_names=iris.target_names,
rounded=True,
filled=True
)

In [39]:
pip install pydot-ng

Note: you may need to restart the kernel to use updated packages.


In [50]:
pip install graphviz

Note: you may need to restart the kernel to use updated packages.


In [ ]:
#conda install -c anaconda graphviz

In [32]:
import os
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

In [49]:
os.getcwd()

'C:\\Users\\Raushan Kumar\\Downloads\\Code'

In [48]:
import pydot

(graph,) = pydot.graph_from_dot_file("C:\\Users\\Raushan Kumar\\Downloads\\Code\\iris_tree.dot")
graph.write_png(path="C:\\Users\\Raushan Kumar\\Downloads\\Code\\iris_tree_1.png",f='png', prog='dot', encoding=None)

In [51]:
>>> tree_clf.predict_proba([[5, 1.5]])

array([[0.        , 0.90740741, 0.09259259]])

In [ ]:
#Increasing min_* hyperparameters or reducing max_* hyperparameters will regularize the model.

In [52]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor(max_depth=2)
tree_reg.fit(X, y)

DecisionTreeRegressor(max_depth=2)

In [53]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [61]:
>>> from sklearn import datasets
>>> iris = datasets.load_iris()
>>> list(iris.keys())
>>> X = iris["data"][:, 3:] # petal width
>>> y = (iris["target"] == 2).astype(np.int)

In [91]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=400)

In [92]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()
voting_clf = VotingClassifier(estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],voting='hard')
voting_clf.fit(X, y)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('rf', RandomForestClassifier()), ('svc', SVC())])

In [87]:
(iris['data']).shape

(150, 4)

In [95]:
>>> from sklearn.metrics import accuracy_score
>>> for clf in (log_clf, rnd_clf, svm_clf, voting_clf):
        clf.fit(x_train, y_train)
        y_pred = clf.predict(x_test)
        print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 1.0
RandomForestClassifier 1.0
SVC 1.0
VotingClassifier 1.0


In [2]:
df = pd.read_csv("C:\\Users\\Raushan Kumar\\Downloads\housing.csv")

NameError: name 'pd' is not defined

In [98]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
num_pipeline = Pipeline([
('imputer', SimpleImputer(strategy="median")),
('std_scaler', StandardScaler()),
])

In [7]:
df['target'] = np.where(df['ocean_proximity']=='NEAR BAY',1,0)

In [108]:
df = df.drop("ocean_proximity",axis = 1)

In [7]:
X= df.iloc[:,0:9]
Y = df['target']

KeyError: 'target'

In [120]:
X=num_pipeline.fit_transform(X)

In [121]:
from sklearn.model_selection import train_test_split

In [122]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.20,random_state=400)

In [126]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()
voting_clf = VotingClassifier(estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],voting='hard')
voting_clf.fit(x_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('rf', RandomForestClassifier()), ('svc', SVC())])

In [127]:
>>> from sklearn.metrics import accuracy_score
>>> for clf in (log_clf, rnd_clf, svm_clf, voting_clf):
        clf.fit(x_train, y_train)
        y_pred = clf.predict(x_test)
        print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.9147286821705426
RandomForestClassifier 0.9953972868217055
SVC 0.9435562015503876
VotingClassifier 0.9491279069767442


In [129]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
bag_clf = BaggingClassifier(
DecisionTreeClassifier(), n_estimators=500,
max_samples=100, bootstrap=True, n_jobs=-1)
bag_clf.fit(x_train, y_train)
y_pred1 = bag_clf.predict(x_test)

In [130]:
accuracy_score(y_test,y_pred1)

0.9670542635658915

In [131]:
>>> bag_clf = BaggingClassifier(
... DecisionTreeClassifier(), n_estimators=500,
... bootstrap=True, n_jobs=-1, oob_score=True)
...
>>> bag_clf.fit(x_train, y_train)
>>> bag_clf.oob_score_

0.9974563953488372

In [133]:
>>> from sklearn.metrics import accuracy_score
>>> y_pred = bag_clf.predict(x_test)
>>> accuracy_score(y_test, y_pred)

0.997577519379845

In [134]:
bag_clf.oob_decision_function_ #decision function returns the class probabilities for each training instance

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [135]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16, n_jobs=-1)
rnd_clf.fit(x_train, y_train)
y_pred_rf = rnd_clf.predict(x_test)

In [136]:
bag_clf = BaggingClassifier(
DecisionTreeClassifier(splitter="random", max_leaf_nodes=16),
n_estimators=500, max_samples=1.0, bootstrap=True, n_jobs=-1)

In [145]:
df.iloc[:,0:9].columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [138]:
rnd_clf.feature_importances_

array([0.54890034, 0.3328988 , 0.0658943 , 0.00144307, 0.00164229,
       0.00184006, 0.00252078, 0.00497502, 0.03988535])

In [154]:
>>> for name, score in zip(df.iloc[:,0:9].columns, rnd_clf.feature_importances_):
        print(name+ str(" : ")+ str(score))

longitude : 0.5489003414236884
latitude : 0.3328988031917658
housing_median_age : 0.06589430110303612
total_rooms : 0.001443065588847754
total_bedrooms : 0.0016422918049883396
population : 0.001840057649878472
households : 0.0025207755299992193
median_income : 0.004975017039575423
median_house_value : 0.03988534666822055


In [155]:
from sklearn.ensemble import AdaBoostClassifier
ada_clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1), n_estimators=200,
algorithm="SAMME.R", learning_rate=0.5)
ada_clf.fit(x_train, y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=0.5, n_estimators=200)

In [157]:
y_pred = ada_clf.predict(x_test)
accuracy_score(y_test, y_pred)

0.9941860465116279

In [181]:
from sklearn.tree import DecisionTreeRegressor
tree_reg1 = DecisionTreeRegressor(max_depth=2)
tree_reg1.fit(X, y)

DecisionTreeRegressor(max_depth=2)

In [179]:
(pd.DataFrame([X[:,0],y[:,0]])).T

0         1
0   1.143683  3.080979
1  -2.799982  3.502402
2   0.796941  2.676702
3   0.811488  3.018898
4   1.537080  4.491661
..       ...       ...
95 -2.018583  2.280040
96  0.800473  3.907612
97 -1.825997  1.566551
98  2.813337  8.309576
99  2.309541  6.361438

[100 rows x 2 columns]

In [180]:
(pd.DataFrame([X[:,0],y[:,0]]))

0         1         2         3         4         5         6   \
0  1.143683 -2.799982  0.796941  0.811488  1.537080 -2.160728 -0.775847   
1  3.080979  3.502402  2.676702  3.018898  4.491661  1.988027  0.739681   

         7         8         9   ...        90        91        92        93  \
0  2.787313 -0.736048  0.907854  ... -2.167163  1.435869 -1.725817  0.997329   
1  8.113684  2.210731  3.083383  ...  1.572693  4.239585  1.626996  3.122737   

         94        95        96        97        98        99  
0  0.582441 -2.018583  0.800473 -1.825997  2.813337  2.309541  
1  4.375263  2.280040  3.907612  1.566551  8.309576  6.361438  

[2 rows x 100 columns]

In [182]:
y2 = y - tree_reg1.predict(X)
tree_reg2 = DecisionTreeRegressor(max_depth=2)
tree_reg2.fit(X, y2)

DecisionTreeRegressor(max_depth=2)

In [183]:
y3 = y2 - tree_reg2.predict(X)
tree_reg3 = DecisionTreeRegressor(max_depth=2)
tree_reg3.fit(X, y3)

DecisionTreeRegressor(max_depth=2)

In [185]:
X_new = 6 * np.random.rand(m, 1) - 3
y_new = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

In [186]:
y_pred = sum(tree.predict(X_new) for tree in (tree_reg1, tree_reg2, tree_reg3))

In [201]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor

In [224]:
X_train, X_val, y_train, y_val = train_test_split(X, y)
gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=120)
gbrt.fit(X_train, y_train)

C:\Users\Raushan Kumar\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GradientBoostingRegressor(max_depth=2, n_estimators=120)

In [225]:
errors = [mean_squared_error(y_val, y_pred)
for y_pred in gbrt.staged_predict(X_val)]
bst_n_estimators = np.argmin(errors)

In [226]:
gbrt_best = GradientBoostingRegressor(max_depth=2,n_estimators=bst_n_estimators)
gbrt_best.fit(X_train, y_train)

C:\Users\Raushan Kumar\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GradientBoostingRegressor(max_depth=2, n_estimators=87)

In [ ]:
gbrt = GradientBoostingRegressor(max_depth=2, warm_start=True)
min_val_error = float("inf")
error_going_up = 0
for n_estimators in range(1, 120):
    gbrt.n_estimators = n_estimators
    gbrt.fit(X_train, y_train)
    y_pred = gbrt.predict(X_val)
    val_error = mean_squared_error(y_val, y_pred)
    if val_error < min_val_error:
        min_val_error = val_error
        error_going_up = 0
    else:
        error_going_up += 1
        if error_going_up == 5:
            break

In [1]:
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [20, 20] # to increase the size of graph

In [ ]:
fig, ax = plt.subplots()
ax.scatter(x_train['YEAR'],y_train)
plt.figure(figsize=(20,20))
#ax.plot([y_test.min(), 30], [y_test.min(), 5], 'k--', lw=1)
ax.set_xlabel('Measured')
ax.set_ylabel('Predicted')
plt.show()

In [1]:
X_centered = X - X.mean(axis=0)
U, s, V = np.linalg.svd(X_centered.dropna())
c1 = V.T[:, 0]
c2 = V.T[:, 1]

NameError: name 'X' is not defined

In [15]:
X['total_bedrooms'].fillna(X['total_bedrooms'].mean(),inplace = True)

In [16]:
X.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [17]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)

In [18]:
pca = PCA()
pca.fit(X)
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1

In [19]:
pca.components_.T[:, 0]

array([-7.98043175e-07, -2.66838390e-06,  1.15177844e-05,  2.53710308e-03,
        1.79836668e-04, -2.41510816e-04,  2.18291633e-04,  1.13282065e-05,
        9.99996712e-01])

In [21]:
pca.explained_variance_ratio_

array([9.99528879e-01, 4.48991297e-04, 1.96100476e-05, 2.26005221e-06,
       2.48945896e-07, 9.94174377e-09, 5.93368208e-10, 9.44165446e-11,
       1.58919442e-11])

In [24]:
#1st method 
pca = PCA()
pca.fit(X)
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum >= 0.95) + 1

In [26]:
pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X)
#elbow plot bw explained variance and dimensions

In [27]:
#compression and decompression is possible by keeping 95% variance
#5% info lost called reconstruction error
pca = PCA(n_components = 154)
X_reduced = pca.fit_transform(X_train)
X_recovered = pca.inverse_transform(X_reduced)

NameError: name 'X_train' is not defined

In [30]:
#best practice to use PCA
from sklearn.decomposition import IncrementalPCA
n_batches = 100
inc_pca = IncrementalPCA(n_components=4)
for X_batch in np.array_split(X, n_batches):
    inc_pca.partial_fit(X_batch)
    X_reduced = inc_pca.transform(X)

In [34]:
rnd_pca = PCA(n_components=8, svd_solver="randomized")
X_reduced = rnd_pca.fit_transform(X)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
clf = Pipeline([
("kpca", KernelPCA(n_components=2)),
("log_reg", LogisticRegression())
])
param_grid = [{
"kpca__gamma": np.linspace(0.03, 0.05, 10),
"kpca__kernel": ["rbf", "sigmoid"]
}]
grid_search = GridSearchCV(clf, param_grid, cv=3)
grid_search.fit(X, y)
>>> print(grid_search.best_params_)

In [1]:
from sklearn.decomposition import KernelPCA
rbf_pca = KernelPCA(n_components = 8, kernel="rbf", gamma=0.04)
X_reduced = rbf_pca.fit_transform(X)

NameError: name 'X' is not defined

In [35]:
rbf_pca = KernelPCA(n_components = 2, kernel="rbf", gamma=0.0433,
fit_inverse_transform=True)
X_reduced = rbf_pca.fit_transform(X)
X_preimage = rbf_pca.inverse_transform(X_reduced)

NameError: name 'KernelPCA' is not defined

In [ ]:
>>> from sklearn.metrics import mean_squared_error
>>> mean_squared_error(X, X_preimage)

In [ ]:
from sklearn.manifold import LocallyLinearEmbedding
lle = LocallyLinearEmbedding(n_components=2, n_neighbors=10)
X_reduced = lle.fit_transform(X)